title: Ashutosh Krishna
#logo: /assets/img/headshot_circle.png
description: Manager - AI @ Siemens Energy
location: Bengaluru, India
email: ashumountain@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal

