title: Ashutosh Krishna
#logo: /assets/img/headshot_circle.png
description: **Manager - AI @ Siemens Energy**
location: Bengaluru, India
email: ashumountain@gmail.com
linkedin: https://www.linkedin.com/in/ashutosh-krishna-84250156
#show_downloads: true
theme: jekyll-theme-minimal

